// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NegosudAPI.Data;

#nullable disable

namespace NegosudAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221014195449_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NegosudAPI.Models.ArticleFolder.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("IdFamily")
                        .HasColumnType("int")
                        .HasColumnName("id_family");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<float>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("IdFamily");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("NegosudAPI.Models.ArticleFolder.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("NegosudAPI.Models.EntityFolder.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("adress");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("Complement")
                        .HasColumnType("longtext")
                        .HasColumnName("complement");

                    b.Property<string>("FistName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mail");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("NegosudAPI.Models.EntityFolder.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mail");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NegosudAPI.Models.EntityFolder.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("adress");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("CompagnyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("compagny_name");

                    b.Property<string>("Complement")
                        .HasColumnType("longtext")
                        .HasColumnName("complement");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mail");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("NegosudAPI.Models.OrderFolder.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("date");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    b.Property<float>("Sum")
                        .HasColumnType("float")
                        .HasColumnName("sum");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("NegosudAPI.Models.OrderFolder.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("date");

                    b.Property<int>("IdVendor")
                        .HasColumnType("int")
                        .HasColumnName("id_vendor");

                    b.HasKey("Id");

                    b.HasIndex("IdVendor");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("NegosudAPI.Models.RelationFolder.Content", b =>
                {
                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("IdPurchaseOrder")
                        .HasColumnType("int")
                        .HasColumnName("id_purchase_order");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("NegosudAPI.Models.RelationFolder.Contents", b =>
                {
                    b.Property<int>("IdBill")
                        .HasColumnType("int")
                        .HasColumnName("id_bill");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("NegosudAPI.Models.RelationFolder.Manage", b =>
                {
                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.ToTable("Manage");
                });

            modelBuilder.Entity("NegosudAPI.Models.ArticleFolder.Article", b =>
                {
                    b.HasOne("NegosudAPI.Models.ArticleFolder.Family", "Family")
                        .WithMany()
                        .HasForeignKey("IdFamily")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("NegosudAPI.Models.OrderFolder.Bill", b =>
                {
                    b.HasOne("NegosudAPI.Models.EntityFolder.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("NegosudAPI.Models.OrderFolder.PurchaseOrder", b =>
                {
                    b.HasOne("NegosudAPI.Models.EntityFolder.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("IdVendor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });
#pragma warning restore 612, 618
        }
    }
}
